source 'https://rubygems.org'

gem 'librarian'
gem 'chef'
gem 'spork'
gem 'rspec'
gem 'rspec-chef', :git => 'git@github.com:inscitiv/rspec-chef.git'
gem 'ruby-augeas'
gem 'ruby-ldap'
gem 'ci_reporter'
